# Site settings
name: Shridhish Sundaran
email: shridhish7@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "shridhish, shridhish, Software Engineer, JAVA, SQL, C++, back- end software engineer, Shridhish Ramath Sundaran, Shridhish website, Shridhish RS, Shridhish"
skills: "Software Engineer in Cincinnati, Ohio"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/shridhish/
  - title: github
    url: https://github.com/shridhish
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
